/**
 * Donations go through the Peakly website, whose server holds the Stripe key.
 * The app only links there, so no payment secret is ever in this open-source code,
 * and copies run by other people still send donations to the project.
 */
export const DONATE_URL = "https://getpeakly.app/donate";

/** Schedule a one-to-one with Peakly's creator. */
export const CALENDLY_URL = "https://calendly.com/alexander-landaverde01/one-to-one";

/**
 * Feedback lives on a VoteWant board (votewant.com): people request features, report bugs
 * and vote. It's the one cloud feature; nothing about the user's apps or keys is sent there.
 * The board ID is generated by VoteWant for the Peakly property (Setup page → widget snippet's
 * data-board). Hosts can override it (NEXT_PUBLIC_VOTEWANT_BOARD / VITE_VOTEWANT_BOARD).
 */
export const VOTEWANT_ORIGIN = "https://votewant.com";
export const DEFAULT_FEEDBACK_BOARD = "getpeakly-com-a180b4a4";

/** Peakly's accent (--accent in globals.css), so the board's buttons and links match the app. */
export const FEEDBACK_BOARD_ACCENT = "2a78d6";

/** The configured board ID, or null when it isn't a plain VoteWant board ID. */
export function feedbackBoardId(board: string | undefined): string | null {
  const id = (board ?? "").trim() || DEFAULT_FEEDBACK_BOARD;
  return /^[A-Za-z0-9_-]+$/.test(id) ? id : null;
}

/** The board's public page in Peakly's colors, or null when no valid board ID is configured. */
export function feedbackBoardUrl(board: string | undefined): string | null {
  const id = feedbackBoardId(board);
  return id ? `${VOTEWANT_ORIGIN}/boards/${encodeURIComponent(id)}?accent=${FEEDBACK_BOARD_ACCENT}` : null;
}
