/**
 * Donations go through the Peakly website, whose server holds the Stripe key.
 * The app only links there, so no payment secret is ever in this open-source code,
 * and copies run by other people still send donations to the project.
 */
export const DONATE_URL = "https://getpeakly.app/donate";

/**
 * Feedback lives on a VoteWant board (votewant.com): people request features, report bugs
 * and vote. It's the one cloud feature; nothing about the user's apps or keys is sent there.
 * The board ID is generated by VoteWant for the Peakly property (Setup page → widget snippet's
 * data-board). Hosts can override it (NEXT_PUBLIC_VOTEWANT_BOARD / VITE_VOTEWANT_BOARD).
 */
export const VOTEWANT_ORIGIN = "https://votewant.com";
export const DEFAULT_FEEDBACK_BOARD = "";

/** The board's public page, or null when no valid board ID is configured. */
export function feedbackBoardUrl(board: string | undefined): string | null {
  const id = (board ?? "").trim() || DEFAULT_FEEDBACK_BOARD;
  return /^[A-Za-z0-9_-]+$/.test(id) ? `${VOTEWANT_ORIGIN}/boards/${encodeURIComponent(id)}` : null;
}
